name: mono_flutter
description: A Flutter plugin integrating the official android and ios SDK for Mono https://mono.co
version: 1.0.0-dev.2
homepage: https://github.com/wiseminds/mono-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter  
  webview_flutter: ^3.0.0
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  # plugin_platform_interface: ^2.0.0
 
flutter:
  plugin:
    implements: mono_flutter
    platforms:
      web:
        pluginClass: MonoFlutterWeb
        fileName: mono_flutter_web.dart
