name: mono_flutter
description: A Flutter plugin integrating the official android and ios SDK for Mono https://mono.co
version: 0.0.5
homepage: https://github.com/wiseminds/mono-flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

 
flutter: 